#ifndef   __DATAPHRASE_H__
#define   __DATAPHRASE_H__

#include   "board.h"
#include   "rtdef.h"
extern uint32_t   respMid;

const static char  typeHeadDown[][30]={
	"PROPERTIES_HEART_RESP",
	"PROPERTIES_REG_RESP",
	"PROPERTIES_485DATA_REP_RESP",
	"PROPERTIES_485DATA_GET",
	"PROPERTIES_485DATA_SET",
	"PROPERTIES_ANADATA_REP_RESP",
	"PROPERTIES_ANADATA_GET",
	"PROPERTIES_485TIM_GET",
	"PROPERTIES_485TIM_SET",
	"PROPERTIES_ANATIM_GET",
	"PROPERTIES_ANATIM_SET",
	"PROPERTIES_485TH_GET",
	"PROPERTIES_485TH_SET",
	"PROPERTIES_ANATH_GET",
	"PROPERTIES_ANATH_SET",
	"PROPERTIES_INPUT_REP_RESP",
	"PROPERTIES_INPUT_GET",
	"PROPERTIES_OUTPUT_REP_RESP",
	"PROPERTIES_OUTPUT_GET",
	"PROPERTIES_OUTPUT_SET",
	"SERVICES_CTRLCFG_READ",
	"SERVICES_CTRLCFG_ADD",
	"SERVICES_CTRLCFG_DEL",
	"SERVICES_DEV_REBOOT",
	"SERVICES_ACU_REBOOT",
	"SERVICES_HISTORY_READ",
	"SERVICES_OTA_WRITE",
	"SERVICES_SAVE",
	"EVENTS_485_ALARM_RESP",
	"EVENTS_ANA_ALARM_RESP"

};
//没有枚举完
typedef enum
{
		PROPERTIES_HEART_RESP=0,
		PROPERTIES_REG_RESP,
		PROPERTIES_485DATA_REP_RESP,
		PROPERTIES_485DATA_GET,
		PROPERTIES_485DATA_SET,
		PROPERTIES_ANADATA_REP_RESP,
		PROPERTIES_ANADATA_GET,
		PROPERTIES_485TIM_GET,
		PROPERTIES_485TIM_SET,
		PROPERTIES_ANATIM_GET,
		PROPERTIES_ANATIM_SET,
		PROPERTIES_485TH_GET,
		PROPERTIES_485TH_SET,
		PROPERTIES_ANATH_GET,
		PROPERTIES_ANATH_SET,
		PROPERTIES_INPUT_REP_RESP,
		PROPERTIES_INPUT_GET,
		PROPERTIES_OUTPUT_REP_RESP,
		PROPERTIES_OUTPUT_GET,
		PROPERTIES_OUTPUT_SET,
		SERVICES_CTRLCFG_READ,
		SERVICES_CTRLCFG_ADD,
		SERVICES_CTRLCFG_DEL,
		SERVICES_DEV_REBOOT,
		SERVICES_ACU_REBOOT,
		SERVICES_HISTORY_READ,
		SERVICES_OTA_WRITE,
		SERVICES_SAVE,
		EVENTS_485_ALARM_RESP,
		EVENTS_ANA_ALARM_RESP,
	  ERRRESP=0xff
}packTypeEnum;












#endif



